### ISSUE TITLE
Add support for virtual USB drives

### ISSUE THREAD

**Issue by upintheairsheep** [lvcabral/brs-engine#142]
https://developer.roku.com/docs/developer-program/getting-started/architecture/file-system.md
It would be nice to get the ability to add "fake" USB paths so you could use media players or theme that Snake game.

**Comment by lvcabral** [comment]
I will implement this, probably using one of these libraries:
https://www.npmjs.com/package/browserfs
https://www.npmjs.com/package/@sirhall/browserfs

**Comment by lvcabral** [comment]
Implemented by #403
