### ISSUE TITLE
RegEx "g" modifier is not supported

### ISSUE THREAD

**Issue by Matt-Moores** [lvcabral/brs-engine#167]
Even though it is not explicitly stated in the documentation Roku regex should support regular expressions documented in the PCRE

https://perldoc.perl.org/perlre#Modifiers

 "ig"= case insensitive global search
```brs
   line="line of text with ${variable} that needs matched and replaced "
   regexline = CreateObject( "roRegex", "\$(\!?\!?)\{([a-zA-Z][_\w]*)\}", "ig" )
   match = regexline.match(line)
   matched = match[0]
   capitalize=match[1]
   variable=match[2]
```
I use this for a variable replacement in strings of text in my dialog system.

**Comment by lvcabral** [comment]
This was an easy fix, will be available on next release.
