### ISSUE TITLE
all files are placed in source folder for some reason.

### ISSUE THREAD

**Issue by georgejecook** [lvcabral/brs-engine#392]
Due to this code

```
 if (sourceCode) {
                    source.push(sourceCode.toString());
                    paths.push({ id: id, url: `source/${fileName}`, type: "source" });
                    id++;
                }
```

Any mechanism for a means of putting files in a different path?

**Comment by lvcabral** [comment]
As currently the engine does not support `SceneGraph` components, the only folder that needs to be parsed is `source` any brightscript file outside would not be in scope.
